
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "publish.sh"
  - "worknenjoy.iml"
  - ".git"
  - ".gitignore"
  - "publish.sh"

gems:
  - jekyll-multiple-languages-plugin

languages: ["en", "pt-BR"]
#exclude_from_localizations: ["javascript", "images", "css"]


# Site settings
title: Work n Enjoy
subtitle: "A Startup that create solutions for remote working"
url: "http://worknenjoy.com" # the base hostname & protocol for your site
baseurl: "" # Set this value to "" if you want your site to be root
cover: "/assets/cover.png"
logo: "/assets/logo.png"

timezone:      null
show_drafts: true
limit_posts: 0
future:      false
unpublished: true

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-114655639-2"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
