
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

gems:
  - jekyll-multiple-languages-plugin

languages: ["en", "br"]
exclude_from_localizations: ["javascript", "images", "css"]


# Site settings
title: Work n Enjoy
subtitle: "A Startup that create solutions for remote working"
url: "http://worknenjoy.github.io/" # the base hostname & protocol for your site
baseurl: "" # Set this value to "" if you want your site to be root
baseurl: "/airspace-jekyll"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
