# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  docs:
    docker:
    - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              git add . && git commit -m 'build page' && git push origin master && git push origin --delete gh-pages && git subtree push --prefix _site/ origin gh-pages
            fi

workflows:
  version: 2
  build-all:
    jobs:
      - docs:
          filters:
            branches:
              only: master